name: Deploy to Render

on:
  push:
    branches:
      - main  # Change "main" si ta branche principale a un autre nom
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trigger Render Deployment
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cv6li7d2ng1s73fv4i4g?key=aph_5hNEhu0"
