name: Deploy to Render

on:
  push:
    branches:
      - main  # Change "main" si ta branche principale a un autre nom

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install  # Remplace par "npm install" si tu utilises npm

      - name: Trigger Render Deploy
        run: curl -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
